# On newly (re)opened issue we label it as New. It goes to the Project Triage where it waits to be triaged and dealt with.

name: Label new or reopened issues with label New

# Controls when the workflow will run
on:
  # Trigger workflow on events with issues
  issues:
    # Define what type of issue events trigger the workflow
    types:
      - reopened
      - opened

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # First job is dealing with labeling the issue in question 
  label_issues:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Set up the permissions
#    permissions:
#      issues: write
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Label issues
        uses: andymckay/labeler@1.0.4
        with:
          add-labels: 'New, Needs Triage'
#          repo-token: ${{ secrets.GITHUB_TOKEN }}
