# Modify release documents, create release assets and generate release when there is a push on master using new tag

name: Create new release

# Controls when the workflow will run
on:
  # Triggers the workflow on push events on the master branch when there is new tag
  push:
    branches:
      - master
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build" with multiple steps
  build:
    # Only activate build on event in master branch
    if: github.event.base_ref == 'refs/heads/master'
    
    name: Create new release
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Check out the code
      - name: Checkout code
        uses: actions/checkout@v2
      
#      # Create the new release
#      - name: Create Release
#        id: create_release
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
#        with:
#          tag_name: ${{ github.ref }}
#          release_name: Release ${{ github.ref }}
#          body: |
#            Changes in this Release
#            - First Change
#            - Second Change
#          draft: false
#          prerelease: false
